

nama_saya = input("Input your name :") 
nim_saya = input ("Input your NIM : ")  


print ("..............................")
print (".......Welcome to",(nama_saya),".............")
print (".......With your NIM ",(nim_saya),".........")


print()
print()
print()
print()


print ('--------------------------------------------')
print ('...program mencari luas-luas bangun datar...')
print ('--------------------------------------------')
print()
print()

print ("Question No.1")
print ("Diketahui sisi = 6, sebutkan Nama da hitunglah luas Bangun datar tersebut!")
persegi = input("Nama Bangun datar tersebut : ")
i =float(input("sisi :"))
x =float(input("sisi :"))
print ("Bangun datar tersebut adalah",persegi,"dan luas bangun datar tersebut adalah ",i *x  )
print()
print()

print ("Question No.2")
print ("Diketahui alas  = 7,Tinggi = 8 , Hitunglah luas Bangun datar tersebut!")
bd1 = input("Nama Bangun datar tersebut : ")
a =eval(input("Alas :"))
b =eval(input("Tinggi :"))
print ("Bangun datar tersebut adalah",bd1,"dan luas bangun datar tersebut adalah ",a*b/2)
print()
print()

print ("Question No.3")
print ("Diketahui Panjang = 4 , Lebar = 9, Sebutkan Nama dan hitunglah Luas Bangun datar tersebut!")
bd2 = input("Nama Bangun datar tersebut : ")
c =eval(input("panjang :"))
d =eval(input("Lebar :"))
print ("Bangun datar tersebut adalah",bd2,"dan luas bangun datar tersebut adalah ",c*d)
print()
print()

print ("Question No.4")
print ("Diketahui Jari-jari = 56 , Sebutkan Nama dan hitunglah Luas Bangun datar tersebut!")
bd4 = input("Nama Bangun datar tersebut : ")
e =eval(input("π :"))
f =eval(input("r :"))
print ("Bangun datar tersebut adalah",bd4,"dan luas bangun datar tersebut adalah ",e*f*f)
print()
print()

print ("Question No.5")
print ("Diketahui Diagonal I = 4 , Diagonal II = 8, Sebutkan Nama dan hitunglah Luas Bangun datar tersebut!")
bd5 = input("Nama Bangun datar tersebut : ")
g =eval(input("Diagonal I :"))
h =eval(input("Diagonal II :"))
print ("Bangun datar tersebut adalah",bd5,"dan luas bangun datar tersebut adalah ",g*h/2)
print()
print()

print ("Question No.6")
print ("Diketahui Sisi AB dan CD sejajar, sisi Ab = 6, sisi CD = 8, tinggi = 3. Sebutkan Nama dan hitunglah Luas Bangun datar tersebut!")
bd6 = input("Nama Bangun datar tersebut : ")
g =eval(input("Sisi AB :"))
h =eval(input("Sisi CD :"))
i =eval(input("Tinggi :"))
print ("Bangun datar tersebut adalah",bd6,"dan luas bangun datar tersebut adalah ",(g+h)*i/2)
print()
print()

print ("Question No.7")
print ("Diketahui Jajargenjang dengan alas = 9, Tinggi = 7, nhitunglah Luas Bangun datar tersebut!")
j=eval(input("Alas :"))
k =eval(input("Tinggi :"))
print (" luas bangun datar jajargenjang  adalah ",j*k)
print()
print()

print ('--------------------------------------------')
print ('....Syukron, Jazakumullah khairankatsiran...')
print ('--------------------------------------------')